name: flutter_templates
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.0+17

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_config: ^2.0.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.0.3
  go_router: ^4.1.0
  intl: ^0.17.0
  json_annotation: ^4.5.0
  package_info_plus: ^1.4.2
  permission_handler: ^8.3.0
  retrofit: ^3.0.1+1

dev_dependencies:
  build_runner: ^2.1.11
  flutter_gen_runner: ^4.3.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  integration_test:
    sdk: flutter
  json_serializable: ^6.2.0
  mockito: ^5.2.0
  retrofit_generator: ^4.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: neuzeit
      fonts:
        - asset: assets/fonts/neuzeit.otf
