name: ios-deploy-to-staging
on:
  # Trigger the workflow on push action
  push:
    branches:
      - develop

jobs:
  build_and_upload_staging_app_to_firebase:
    name: Build And Upload iOS Staging Application To Firebase
    runs-on: macOS-latest
    environment: staging
    env:
      TEAM_ID: ${{#mustacheCase}}secrets.TEAM_ID{{/mustacheCase}}
      FASTLANE_USER: ${{#mustacheCase}}secrets.FASTLANE_USER{{/mustacheCase}}
      FASTLANE_PASSWORD: ${{#mustacheCase}}secrets.FASTLANE_PASSWORD{{/mustacheCase}}
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{#mustacheCase}}secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD{{/mustacheCase}}
      FASTLANE_SESSION: ${{#mustacheCase}}secrets.FASTLANE_SESSION{{/mustacheCase}}
      MATCH_PASSWORD: ${{#mustacheCase}}secrets.MATCH_PASSWORD{{/mustacheCase}}
      KEYCHAIN_PASSWORD: ${{#mustacheCase}}secrets.KEYCHAIN_PASSWORD{{/mustacheCase}}
      FIREBASE_CLI_TOKEN: ${{#mustacheCase}}secrets.FIREBASE_CLI_TOKEN{{/mustacheCase}}
      FIREBASE_APP_ID: ${{#mustacheCase}}vars.FIREBASE_IOS_APP_ID{{/mustacheCase}}
      FIREBASE_DISTRIBUTION_TESTER_GROUPS: ${{#mustacheCase}}vars.FIREBASE_DISTRIBUTION_TESTER_GROUPS{{/mustacheCase}}
      GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{#mustacheCase}}secrets.SSH_PRIVATE_KEY{{/mustacheCase}}

      - name: Set up Flutter environment
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.10.5'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Set up .env.staging
        env:
          ENV: ${{#mustacheCase}}secrets.ENV{{/mustacheCase}}
        run: |
          echo -e "$ENV" > .env.staging

      - name: Run code generator
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Bundle install
        run: cd ./ios && bundle install

      - name: Pod install
        run: cd ./ios && pod install

      - name: Match Adhoc
        run: cd ./ios && bundle exec fastlane sync_adhoc_staging_signing

      - name: Deploy to Firebase
        run: |
          cd ./ios && bundle exec fastlane build_and_upload_staging_app
