name: Bump Version

on:
  workflow_dispatch:
    inputs:
      newVersion:
        description: "New version"
        required: true
        type: string

jobs:
  bump_version:
    name: Bump version
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set new version
        run: |
          perl -i -pe 's/^(version:\s+\d+\.\d+\.\d+\+)(\d+)$/"version: ${{#mustacheCase}}github.event.inputs.newVersion{{/mustacheCase}}+".($2+1)/e' ./pubspec.yaml

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          assignees: ${{#mustacheCase}}secrets.GITHUB_USER{{/mustacheCase}}
          token: ${{#mustacheCase}}secrets.WIKI_ACTION_TOKEN{{/mustacheCase}}
          commit-message: Bump version to ${{#mustacheCase}}github.event.inputs.newVersion{{/mustacheCase}}
          committer: Nimble Bot <bot@nimblehq.co>
          branch: chore/bump-version-to-${{#mustacheCase}}github.event.inputs.newVersion{{/mustacheCase}}
          delete-branch: true
          title: '[Chore] Bump version to ${{#mustacheCase}}github.event.inputs.newVersion{{/mustacheCase}}'
          labels: |
            type : chore
          body: |
            ## What happened 👀

            Bump version to ${{#mustacheCase}}github.event.inputs.newVersion{{/mustacheCase}}

            ## Insight 📝

            Automatically created by the Bump Version workflow.

            ## Proof Of Work 📹

            On the Files changed tab
