# For setup instruction, refer to https://github.com/nimblehq/github-actions-workflows/blob/main/.github/workflows/publish_wiki.yml
name: Publish Wiki

on:
  push:
    paths:
      - .github/wiki/**
    branches:
      - develop

jobs:
  publish:
    name: Publish Wiki
    uses: nimblehq/github-actions-workflows/.github/workflows/publish_wiki.yml@0.1.0
    with:
      USER_NAME: github-wiki-workflow
      USER_EMAIL: ${{#mustacheCase}}secrets.GH_EMAIL{{/mustacheCase}}
    secrets:
      USER_TOKEN: ${{#mustacheCase}}secrets.GH_TOKEN{{/mustacheCase}}
