# frozen_string_literal: true

require './Constants/Constants'
require './Constants/Environments'
require './Managers/BuildManager'
require './Managers/DistributionManager'
require './Managers/MatchManager'

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"

builder = BuildManager.new(fastlane: self)

distribution_manager = DistributionManager.new(
  fastlane: self,
  build_path: Constants.BUILD_PATH,
  firebase_token: Environments.FIREBASE_CLI_TOKEN
)

match_manager = MatchManager.new(
  fastlane: self,
  keychain_name: Constants.KEYCHAIN_NAME,
  keychain_password: Constants.KEYCHAIN_PASSWORD,
  is_ci: Environments.CI
)

before_all do
  ensure_bundle_exec
end

default_platform(:ios)

platform :ios do

  # Code Sign

  desc 'Sync AppStore Staging match signing'
  lane :sync_appstore_staging_signing do
    match_manager.sync_app_store_signing(app_identifier: [Constants.BUNDLE_ID_STAGING])
  end

  desc 'Sync Adhoc Staging match signing'
  lane :sync_adhoc_staging_signing do
    match_manager.sync_adhoc_signing(app_identifier: [Constants.BUNDLE_ID_STAGING])
  end

  desc 'Sync AppStore Production match signing'
  lane :sync_appstore_production_signing do
    match_manager.sync_app_store_signing(app_identifier: [Constants.BUNDLE_ID_PRODUCTION])
  end

  desc 'Register new devices'
  lane :register_new_device do
    device_name = prompt(text: 'Enter the device name: ')
    device_udid = prompt(text: 'Enter the device UDID: ')
    device_hash = {}
    device_hash[device_name] = device_udid
    register_devices(devices: device_hash)
    match(force: true)
  end

  # Testflight

  desc 'Build and upload Staging app to Test Flight'
  lane :build_and_upload_testflight_app do
    set_app_version
    bump_build
    builder.build_app_store(
      Constants.SCHEME_NAME_STAGING,
      Constants.PRODUCT_NAME_STAGING,
      Constants.BUNDLE_ID_STAGING,
      false
    )
    upload_build_to_testflight
  end

  desc 'upload develop build to Test Flight'
  private_lane :upload_build_to_testflight do
    distribution_manager.upload_to_testflight(
      product_name: Constants.PRODUCT_NAME_STAGING,
      bundle_identifier: Constants.BUNDLE_ID_STAGING
    )
  end

  desc 'Build and upload Production app to Test Flight'
  lane :build_and_upload_testflight_production_app do
    set_app_version
    bump_build
    builder.build_app_store(
      Constants.SCHEME_NAME_PRODUCTION,
      Constants.PRODUCT_NAME_PRODUCTION,
      Constants.BUNDLE_ID_PRODUCTION,
      false
    )
    set_app_store_connect_api_key
    upload_production_build_to_testflight
  end

  desc 'Upload Production build to Test Flight'
  private_lane :upload_production_build_to_testflight do
    distribution_manager.upload_to_testflight(
      product_name: Constants.PRODUCT_NAME_PRODUCTION,
      bundle_identifier: Constants.BUNDLE_ID_PRODUCTION,
    )
  end

  # AppStore

  desc 'Build and upload Staging app to App Store Connect'
  lane :build_and_upload_app_store_connect_app do
    set_app_version
    bump_build
    builder.build_app_store(
      Constants.SCHEME_NAME_STAGING,
      Constants.PRODUCT_NAME_STAGING,
      Constants.BUNDLE_ID_STAGING,
      false
    )
    upload_build_to_app_store_connect
  end

  desc 'upload develop build to App Store Connect'
  private_lane :upload_build_to_app_store_connect do
    distribution_manager.upload_to_app_store_connect(
      product_name: Constants.PRODUCT_NAME_STAGING,
      bundle_identifier: Constants.BUNDLE_ID_STAGING
    )
  end

  desc 'Build and upload Production app to App Store Connect'
  lane :build_and_upload_production_app_store_connect_app do
    set_app_version
    bump_build
    builder.build_app_store(
      Constants.SCHEME_NAME_PRODUCTION,
      Constants.PRODUCT_NAME_PRODUCTION,
      Constants.BUNDLE_ID_PRODUCTION,
      false
    )
    set_app_store_connect_api_key
    upload_build_to_production_app_store_connect
  end

  desc 'upload production build to App Store Connect'
  private_lane :upload_build_to_production_app_store_connect do
    distribution_manager.upload_to_app_store_connect(
      product_name: Constants.PRODUCT_NAME_PRODUCTION,
      bundle_identifier: Constants.BUNDLE_ID_PRODUCTION
    )
  end

  # Firebase
  desc 'Build and upload Staging app to Firebase'
  lane :build_and_upload_staging_app do
    build_and_upload_to_firebase(
      scheme_name: Constants.SCHEME_NAME_STAGING,
      product_name: Constants.PRODUCT_NAME_STAGING,
      bundle_id: Constants.BUNDLE_ID_STAGING,
      app_id: Environments.FIREBASE_APP_ID
    )
  end

  desc 'build and upload app to Firebase'
  private_lane :build_and_upload_to_firebase do |options|
    set_app_version
    bump_build
    builder.build_ad_hoc(
      options[:scheme_name],
      options[:product_name],
      options[:bundle_id]
    )
    upload_build_to_firebase(
      product_name: options[:product_name],
      firebase_app_id: options[:app_id],
      tester_groups: Environments.FIREBASE_TESTER_GROUPS
    )
  end

  desc 'Set App Store Connect API key'
  lane :set_app_store_connect_api_key do
    app_store_connect_api_key(
      key_id: Environments.APP_STORE_KEY_ID,
      issuer_id: Environments.APP_STORE_ISSUER_ID,
      key_content: Environments.APP_STORE_CONNECT_API_KEY_BASE64,
      is_key_content_base64: true
    )
  end

  # Private helper lanes

  desc 'check if any specific version number in build environment'
  private_lane :set_app_version do
    # Set up env var MANUAL_VERSION if we need to override the version number
    if (Environments.MANUAL_VERSION || '') != ''
      increment_version_number(
        version_number: Environments.MANUAL_VERSION
      )
    end
  end

  desc 'set build number with the run number'
  private_lane :bump_build do
    increment_build_number(
      build_number: Environments.GITHUB_RUN_NUMBER,
      xcodeproj: Constants.PROJECT_PATH
    )
  end

  desc 'upload develop build to Firebase app distribution'
  private_lane :upload_build_to_firebase do |options|
    distribution_manager.upload_to_firebase(
      product_name: options[:product_name],
      firebase_app_id: options[:firebase_app_id],
      tester_groups: options[:tester_groups],
      notes: Environments.RELEASE_NOTE_CONTENT
    )
  end
end
