codecov:
  bot: [bot_username] # For the private repository, set up a TeamBot https://docs.codecov.com/docs/team-bot, e.g., bob
  require_ci_to_pass: yes

coverage:
  status:
    project: off
    patch: off

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,tree"
  behavior: default
  require_changes: no

ignore:
  - "lib/di"
  - "lib/gen"
