name: ios-deploy-to-staging
on:
  # Trigger the workflow on push action
  push:
    branches:
      - develop

jobs:
  build_and_upload_staging_app_to_firebase:
    name: Build And Upload iOS Staging Application To Firebase
    runs-on: macOS-latest
    environment: staging
    env:
      TEAM_ID: ${{ secrets.TEAM_ID }}
      FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
      FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      FIREBASE_APP_ID: ${{ vars.FIREBASE_IOS_APP_ID }}
      FIREBASE_DISTRIBUTION_TESTER_GROUPS: ${{ vars.FIREBASE_DISTRIBUTION_TESTER_GROUPS }}
      GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Flutter environment
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.10.5'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Set up .env.staging
        env:
          ENV: ${{ secrets.ENV }}
        run: |
          echo -e "$ENV" > .env.staging

      - name: Run code generator
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Bundle install
        run: cd ./ios && bundle install

      - name: Pod install
        run: cd ./ios && pod install

      - name: Match Adhoc
        run: cd ./ios && bundle exec fastlane sync_adhoc_staging_signing

      - name: Deploy to Firebase
        run: |
          cd ./ios && bundle exec fastlane build_and_upload_staging_app
